// <auto-generated />
namespace Foothill.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.1-30610")]
    public sealed partial class remove_DOB : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(remove_DOB));
        
        string IMigrationMetadata.Id
        {
            get { return "201902070625382_remove_DOB"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
